/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACalendar: typeof import('@arco-design/web-vue')['Calendar']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AListItemMeta: typeof import('@arco-design/web-vue')['ListItemMeta']
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    Bubbles: typeof import('./src/components/Bubbles/Bubbles.vue')['default']
    Calendar: typeof import('./src/components/Calendar/Calendar.vue')['default']
    CalendarGrid: typeof import('./src/components/Calendar/CalendarGrid.vue')['default']
    CalendarHeader: typeof import('./src/components/Calendar/CalendarHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputPage: typeof import('./src/components/InputPage/InputPage.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
  }
}
