/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('@arco-design/web-vue')['Col']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AMonthPicker: typeof import('@arco-design/web-vue')['MonthPicker']
    ARow: typeof import('@arco-design/web-vue')['Row']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    Bubbles: typeof import('./src/components/Bubbles/Bubbles.vue')['default']
    Calendar: typeof import('./src/components/Calendar/Calendar.vue')['default']
    CalendarGrid: typeof import('./src/components/Calendar/CalendarGrid.vue')['default']
    CalendarHeader: typeof import('./src/components/Calendar/CalendarHeader.vue')['default']
    Chart: typeof import('./src/components/Chart/Chart.vue')['default']
    ChartPage: typeof import('./src/components/ChartPage/ChartPage.vue')['default']
    DateSelect: typeof import('./src/components/DateSelect/DateSelect.vue')['default']
    DayCard: typeof import('./src/components/DayCard/DayCard.vue')['default']
    DynamicWall: typeof import('./src/components/DynamicWall/DynamicWall.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    InputPage: typeof import('./src/components/InputPage/InputPage.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
  }
}
